### ISSUE TITLE
Incorrect sciserver version number in sciserver.org frontpage

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SciServer-WordPress-Website#2]
Says it is 1.8.4,  should say 1.8.2 (last september)

**Comment by bonbons0220** [comment]
Looks like Jordan fixed it.

**Comment by mtaghiza** [comment]
It's not fixed, take a look at the frontpage.

**Comment by bonbons0220** [comment]
[image: Inline image 1]

Bonnie Souter PhD

Associate Research Scientist

Institute for Data Intensive Engineering and Science

Johns Hopkins University

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by bonbons0220** [comment]
Manu please provide a link to the page that has the incorrect version # on
it.

Bonnie Souter PhD

Associate Research Scientist

Institute for Data Intensive Engineering and Science

Johns Hopkins University

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by mtaghiza** [comment]
www.sciserver.org  , to the left of the log in button, it says 1.8.4

**Comment by bonbons0220** [comment]
Thanks. I got it backwards what you were trying to say. Thought you were
saying it should be 1.8.4 and that's what it is. My mistake.

Bonnie Souter PhD

Associate Research Scientist

Institute for Data Intensive Engineering and Science

Johns Hopkins University

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by mtaghiza** [comment]
no problem
