### ISSUE TITLE
Update SciServer version to v1.9.3 

### ISSUE THREAD

**Issue by bonbons0220** [sciserver/SciServer-WordPress-Website#3]
Update SciServer version to v1.9.3 on the Splash Page in **test.sciserver.org** and in the Support/Help section, as needed.

There are no user-facing changes to document.
There are no (user-facing) Bug Fixes to document. 

When done, DO NOT CLOSE ISSUE, instead

Mark as FIXED,
Add comment with commit hash
Assign to (bonbons0220)

**Comment by raddick** [comment]
Fixed in test.sciserver.org dashboard back-end. See

http://test.sciserver.org/support/updates/

**Comment by bonbons0220** [comment]
Pushed test to prod www.sciserver.org on Friday: 20170310_1619.
Includes commit: 4676a614156592d3cbeb632ce49b4aed2542b20f.
