### ISSUE TITLE
Dead link on news page

### ISSUE THREAD

**Issue by raddick** [sciserver/SciServer-WordPress-Website#4]
On the news page, the most recent item (post) has a dead link - the "Releases & updates" link:

http://test.sciserver.org/new-release-sciserver-altair-v1-9-3/

Fixing it now, will reassign to Bonnie once it's fixed.

**Comment by raddick** [comment]
Fixed! There were similar bugs in the archived news posts - I fixed those too.

**Comment by raddick** [comment]
Fixed and pushed to production. I can close this, but not sure what the best practice is since it's now assigned to Bonnie. Will ask Bonnie when  I see her.

Link on production site:

http://www.sciserver.org/news/

**Comment by bonbons0220** [comment]
Fixed in v1.1.12 and 
sciserver-v1.9.4.
