### ISSUE TITLE
Simplify process of updating Release name and version on website

### ISSUE THREAD

**Issue by bonbons0220** [sciserver/SciServer-WordPress-Website#7]
Simplify process of updating Release name and version on website

**Comment by bonbons0220** [comment]
I have updated the way the release name and version # are updated on the www.sciserver.org website. These are now set in the Dashboard, under the Appearance Menu->SciServer Options. 
The release name and version you set are shown on the splash page.
@raddick Please have a look and if it's good to go, please update to v1.10.0 in test.sciserver.org (to be ready for next push).

**Comment by raddick** [comment]
I created a new release post-type for v1.10. Here is the link:

http://test.sciserver.org/release/sciserver-altair-v1-10-0/

The new system works quite smoothly. Thanks @bonbons0220!

I was occasionally unclear about what was "New" and what was an "Update."

Do we also want a type for "deprecated"? Or is "other" enough?

**Comment by bonbons0220** [comment]
Let's keep it simple. Anything that is "Other" can have a note included in the description about deprecated, etc.

If possible I will show it to the Dev team today (monday) and see what they and Mike think.

**Comment by raddick** [comment]
Keeping it as "other" sounds right to me. Thanks.
